version: '3'

services:
    go_video_store:
      build: ./
      container_name: go_video_store
      environment:
         SERVICE_NAME: go_video_store
         SERVICE_TAGS: go_video_store,http,80
      ports:
         - "8190:80"
      volumes:
         - ../:/apps
      networks:
        - go_video_store_network
      working_dir: /apps/go_video_store
      command: /bin/sh -c "make linux_build  && ./main"

networks:
    go_video_store_network:
      # Use a custom driver
      driver: bridge