package dto

type unknownSlice727637754 []string
type List []NoNameObject
type Details []NoNameObject1427828239

type NoNameObject1427828239 struct {
	OfficialWebsite  string  `json:"official_website" form:"official_website"`
	DescriptionUrl   string  `json:"description_url" form:"description_url"`
	Year             int64   `json:"year" form:"year"`
	ReleasedDateStr  string  `json:"released_date_str" form:"released_date_str"`
	VideoPosterUrl   string  `json:"video_poster_url" form:"video_poster_url"`
	PosterCache      string  `json:"poster_cache" form:"poster_cache"`
	TimeStr          string  `json:"time_str" form:"time_str"`
	VideoDescription string  `json:"video_description" form:"video_description"`
	Score            float64 `json:"score" form:"score"`
	PosterListUrl    string  `json:"poster_list_url" form:"poster_list_url"`
	UptDatetime      string  `json:"upt_datetime" form:"upt_datetime"`
	PerUpdateTime    string  `json:"per_update_time" form:"per_update_time"`
	Season           int64   `json:"season" form:"season"`
	Id               int64   `json:"id" form:"id"`
	SetNum           int64   `json:"set_num" form:"set_num"`
	AddDatetime      string  `json:"add_datetime" form:"add_datetime"`
	VideoId          int64   `json:"video_id" form:"video_id"`
}
type NoNameObject struct {
	PrettyName  string  `json:"pretty_name" form:"pretty_name"`
	MetaName    string  `json:"meta_name" form:"meta_name"`
	UptDatetime string  `json:"upt_datetime" form:"upt_datetime"`
	Details     Details `json:"details" form:"details"`
	AddDatetime string  `json:"add_datetime" form:"add_datetime"`
	VideoId     int64   `json:"video_id" form:"video_id"`
}
type VideoResponse struct {
	List List `json:"list" form:"list"`
}

var VideoResponseMock = VideoResponse{
	List: List{
		NoNameObject{
			UptDatetime: "2023-01-28 07:36:09",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35460374",
					TimeStr:          " 30鍒嗛挓",
					UptDatetime:      "2023-01-28 09:02:28",
					SetNum:           12,
					VideoId:          9,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2681862170.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-10-22(闊╁浗)']",
					Score:            9.0,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/35460374/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€璇ュ墽鏀圭紪鑷悓鍚嶆极鐢伙紝璁茶堪涓変釜涓嬬彮鍚庢€昏鍠濅笂涓€鏉厭锛屼互鍠濋厭浣滀负浜虹敓淇″康鐨?30宀佸コ瀛愮殑鏁呬簨銆俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2883935515.webp",
					Id:               27,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 08:40:09",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35681055",
					TimeStr:          "",
					UptDatetime:      "2023-01-28 07:36:09",
					SetNum:           12,
					VideoId:          9,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2884467826.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-12-09(闊╁浗)']",
					Score:            5.5,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/35681055/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€璁茶堪涓変釜濂充汉浠モ€滀竴澶╃粨鏉熸椂涓€鏉厭鈥濅负浜虹敓淇′话鐨勬棩甯告晠浜嬨€俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2883297167.webp",
					Id:               9,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:36:09",
				},
			},
			VideoId:     9,
			PrettyName:  "閰掗閮藉競濂充汉浠? (鏇存柊鑷? 绗?2瀛?12)",
			MetaName:    "閰掗閮藉競濂充汉浠?",
			AddDatetime: "2023-01-28 07:36:09",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 07:40:38",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35128771",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 10:50:48",
					SetNum:           12,
					VideoId:          10,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2624627719.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-04-10(鏃ユ湰)']",
					Score:            7.6,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/35128771/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆岃瀛﹀缁欏紕鍝簡鈥︹€?!!銆嶆煇澶╂斁瀛﹀悗鍋剁劧鍘讳簡鍥句功瀹わ紝鍗村湪閭ｉ噷琚秴绾р€滄姈S鈥濆濡圭粰鐩笂浜嗭紒娆鸿礋銆佸垇闅惧闀匡紝鍚靛惖闂归椆鐨勫ス鐨勫悕瀛楁槸鈥斺€斻€庨暱鐎炲悓瀛︺€忥紒鍙仺鍗村張鍙埍銆傞ケ鍙楄嫤闅惧嵈鍙堟兂闄湪濂硅韩杈广€傝繖鏄浣犵殑鍐呭績鏈変粈涔堜笢瑗胯閱掔殑鈥淪濞囧皯濂斥€濈殑鏁呬簨銆俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2653228108.webp",
					Id:               43,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 10:50:48",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35638119",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-29 08:28:11",
					SetNum:           12,
					VideoId:          10,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2882403838.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-07(鏃ユ湰)']",
					Score:            8.1,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35638119/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆庝笉瑕佹璐熸垜锛岄暱鐎炲悓瀛︺€廡V鍔ㄧ敾绗?2瀛ｅ埗浣滃彂琛╘n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2886173413.webp",
					Id:               10,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:40:38",
				},
			},
			VideoId:     10,
			PrettyName:  "涓嶈娆鸿礋鎴? 闀跨€炲悓瀛? (鏇存柊鑷? 绗?2瀛?04)",
			MetaName:    "涓嶈娆鸿礋鎴戦暱鐎炲悓瀛?",
			AddDatetime: "2023-01-28 07:40:38",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 07:40:50",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/34941837",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 10:50:39",
					SetNum:           20,
					VideoId:          11,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2632657962.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-04-12(鏃ユ湰)']",
					Score:            8.8,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/34941837/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€浣滃搧鏁呬簨鎻忚堪锛屾煇浜烘妸銆岀悆銆嶆斁杩涜繖鐗囧湡鍦般€傚叿澶囨敹闆嗘儏鎶ョ殑鏈鸿兘锛岃繕鍙互鍙樻崲鍚勭澶栬矊锛岄偅涓悆浣撶敋鑷宠繛姝讳骸閮借兘瓒呰秺銆傛煇澶╋紝瀹冮亣瑙佷簡灏戝勾锛屼箣鍚庡張鍒嗗紑銆傚厜绾裤€佸懗閬撱€佸０闊炽€佹俯搴︺€佺棝鑻︺€佸枩鎮︺€佸搥浼も€︹€﹀湪杩欎釜鍏呮弧鍒烘縺鐨勪笘鐣岄噷寰樺緤锛屽睍寮€涓€娈垫案鎭掍箣鏃呫€俓n<br/>\n銆€銆€鐢卞ぇ浠婅壇鏃舵墍鐫€婕敾浣滃搧銆婄粰涓嶇伃鐨勪綘銆嬶紝瀹樻柟浜庝粖1鏈?9鏃ュ甯冩敼缂栫數瑙嗗姩鐢荤殑娑堟伅锛岄瀹氬皢浜?10鏈堝湪鏃ユ湰寮€鎾€俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2632658485.webp",
					Id:               42,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 10:50:39",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35588216",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-29 11:57:36",
					SetNum:           20,
					VideoId:          11,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2879663448.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-10-23(鏃ユ湰)']",
					Score:            8.2,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/35588216/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆婅嚧涓嶇伃鐨勪綘绗簩瀛ｃ€嬪皢浜?2022骞寸瀛ｆ挱閫乗n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2879663448.webp",
					Id:               11,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:40:50",
				},
			},
			VideoId:     11,
			PrettyName:  "缁欎笉鐏殑浣? (鏇存柊鑷? 绗?2瀛?13)",
			MetaName:    "缁欎笉鐏殑浣?",
			AddDatetime: "2023-01-28 07:40:50",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 07:41:00",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/30174419",
					TimeStr:          " 25鍒嗛挓",
					UptDatetime:      "2023-01-28 10:51:02",
					SetNum:           24,
					VideoId:          12,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2558471577.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2019-07-07(鏃ユ湰)']",
					Score:            9.3,
					Year:             2019,
					PosterListUrl:    "https://movie.douban.com/subject/30174419/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鍏厓10涓栫邯鏈湡锛屼笘鐣屽悇鍦板嚭鐜颁簡鍙仛鎴樹簤鎺犲ず鐨勬渶寮烘皯鏃徛风淮浜汉銆傝璁存瓕涓烘渶寮烘垬澹殑鍎垮瓙路鎵樺皵鑺紝鑷皬渚跨敓娲诲湪鎴樺満涓婏紝骞跺悜寰€鐫€姊﹀够澶ч檰鈥滄枃鍏帮紙VINLAND锛夆€濃€斺€擻n<br/>\n銆€銆€杩欐槸涓€涓彂鐢熷湪婵€鑽℃椂浠ｇ殑锛岀湡姝ｇ殑鎴樺＋鐗╄銆俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2549692505.webp",
					Id:               30,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:03:37",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35518839",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 10:48:04",
					SetNum:           24,
					VideoId:          12,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2874307820.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-09(鏃ユ湰)']",
					Score:            9.6,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35518839/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鏂般仧銇崈骞寸磤銈掕繋銇堛仧銉囥兂銉炪兗銈兓銉︺儓銉┿兂銉夊崐宄跺崡閮ㄣ€俓n<br/>\n銆€銆€浠囨暤銉汇偄銈枫偋銉┿儍銉変骸銇嶅緦銆佺敓銇嶃倠鐩殑銈掑け銇ｃ仧銉堛儷銉曘偅銉炽伅銆併€屽ゴ闅枫€嶃仺銇椼仸鍦颁富銉汇偙銉嗐偅銉伀璨枫倧銈屻€佸郊銇屾墍鏈夈仚銈嬭静鍫淬仹闁嬪⒕浣滄キ銇緭浜嬨仐銇︺亜銇熴€俓n<br/>\n銆€銆€銇濄亾銇с€佸悓銇樸亸濂撮毞銇韩鍒嗐伕銇ㄥ爼銇°仧闈掑勾銉汇偍銈ゃ儕銉仺銇嚭浼氥亜銈掋亶銇ｃ亱銇戙伀鑷倝銇岀姱銇椼仧缃仺鍚戙亶鍚堛亜銆佺敓銇嶃倠鎰忓懗銈掕鍑恒仐銇︺亜銇忋€俓n<br/>\n銆€銆€涓€鏂广€併偆銉炽偘銉┿兂銉夌帇銇嵆浣嶃仐銇熴偗銉屻兗銉堛伅銆屾ソ鍦熴€嶃伄寤鸿ō銇悜銇戙仸銆併仌銈夈仾銈嬬増鍥炽伄鎷″ぇ銈掔洰璜栥倱銇с亜銇熴€俓n<br/>\n銆€銆€銇撱倢銇€滄湰褰撱伄鎴﹀＋銇墿瑾?(銈点偓)鈥漒n<br/>\n銆€銆€銉椼儹銉兗銈般伄銇濄伄鍏堛伀銇傘倠鈥滃劅銇勩仺鏁戞笀銇墿瑾?(銈点偓)鈥濄€俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2886472129.webp",
					Id:               12,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:41:00",
				},
			},
			VideoId:     12,
			PrettyName:  "鍐版捣鎴樿 (鏇存柊鑷? 绗?2瀛?03)",
			MetaName:    "鍐版捣鎴樿",
			AddDatetime: "2023-01-28 07:41:00",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 07:41:20",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/34906701",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 09:04:18",
					SetNum:           12,
					VideoId:          13,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2586357638.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2020-01-08(鏃ユ湰)']",
					Score:            7.8,
					Year:             2020,
					PosterListUrl:    "https://movie.douban.com/subject/34906701/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鐢佃杩炵画鍓с€婃潵涓栦細濂藉ソ鍋氱殑銆嬶紙鍗炽€婃潵涓栥仹銇仭銈冦倱銇ㄣ仐銇俱仚銆嬶級灏嗕簬銆?2020骞?1鏈?8鏃ャ€戝湪涓滀含鐢佃鍙帮紝DramaParai绛夋挱鍑恒€傝繖閮ㄥ墽鏄牴鎹€奐UMP銆嬩笂杩炶浇鐨勫悓鍚嶆极鐢绘敼缂栬€屾垚鐨勩€傘€婃潵涓栦細濂藉ソ鍋氱殑銆嬩互CG鍒朵綔鍏徃鐨勩€屼笁瑙掑伐浣滃銆嶄负鑸炲彴锛屾弿鍐欎簡鍦ㄤ笉鍚岀敺濂宠韩涓婂彂鐢熺殑鏁呬簨銆傚叾涓湁瀵规€ч潪甯稿紑鏀惧苟鍚屾椂鎷ユ湁澶氬悕鎬т即渚ｇ殑濂崇敓銆愬ぇ妫姹熴€戯紙鍐呯敯鐞嗗ぎ楗帮級锛屽浜庢棤娉曟垚涓鸿嚜宸辨湰鍛界敺鎬ф亱浜鸿繖涓€浜嬪疄锛屽ス涓€鏂归潰鎰熷埌绌鸿櫄锛屽彟涓€鏂归潰涔熻〃绀恒€岀畻浜嗙畻浜嗭紝涓嬭緢瀛愭垜浼氬ソ濂藉仛鐨勩€嶏紱鏈変笉璐熻矗浠诲湴鐜╁紕濂虫€х殑甯呭摜銆愭澗鐢板仴銆戯紙灏忓叧瑁曞お楗帮級锛涙湁瀵规亱鐖变笉鎰熷叴瓒ｅ枩娆L鐨勯珮鏉夋鍠滄BL銆佸苟鏍囨鈥滄病鏈夌敺鏈嬪弸鐨勫勾鏁?=骞撮緞鈥濈殑澶勫コ銆愰珮鏉夋銆戯紙澶敯鑾夎彍楗帮級锛涜繕鏈夊彈杩囦激瀹充箣鍚庡彧鍠滄澶勫コ鐨勭敺浜恒€愭灄鑳溿€戯紙鍚庤棨鍒氳寖楗帮級鍙婂皢澶ч儴鍒嗘敹鍏ラ兘濂夌尞缁欓淇楀簵鐨勭敺浜虹瓑绛夈€俓n<br/>\n銆€銆€璇ュ墽鐨勭紪鍓у皢鐢便€婃亱涔嬫湀銆嬨€併€婂彧鎯充綇鍦ㄥ悏绁ュ鍚椼€嬬殑缂栧墽娌熷彛鐪?...\n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2635428096.webp",
					Id:               32,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:04:18",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35417716",
					TimeStr:          " 30鍒嗛挓",
					UptDatetime:      "2023-01-28 07:41:27",
					SetNum:           8,
					VideoId:          13,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2676385235.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-08-04(Paravi鍏堣閰嶄俊)', '2021-08-11(鏃ユ湰)']",
					Score:            8.1,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/35417716/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€CG鍒朵綔鍏徃鈥渟tudiodelta鈥濈殑鑱屽憳澶ф．妗冩睙锛堝唴鐢扮悊澶グ锛夋槸鏈変簲涓偖鍙嬬殑鎬т緷瀛樼郴濂冲瓙銆傝涓衡€滄€ф槸涓嶈姳閽辩殑鐖卞ソ鈥濓紝浣嗕笌姝ょ浉鍙嶏紝濂瑰枩娆笂浜嗗湪鍟嗙ぞ宸ヤ綔鐨勬湁濂冲弸鐨凙鍚涳紙濉╅噹鐟涗箙楗帮級銆傚浜庡緱涓嶅埌鍥炴姤鐨勭埍鎯咃紝濂规劅鍒版棤鍙浣曠殑鎮蹭激鍜岀┖铏氥€備絾鐜板湪锛屽ス鐨勫績寮€濮嬪湪A鍚涘拰鍚屼簨鏉剧敯锛堝皬鍏宠澶グ锛変箣闂存憞鎽嗕笉瀹氥€侤鍝︽捀椹紙闃跨偣锛塡n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2673342453.webp",
					Id:               14,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:41:27",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/36171585",
					TimeStr:          "",
					UptDatetime:      "2023-01-28 07:41:20",
					SetNum:           1,
					VideoId:          13,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2886211674.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-12-28(鏃ユ湰)']",
					Score:            8.3,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/36171585/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€璁茶堪妗冩睙锛堝唴鐢扮悊澶グ锛夊拰鏉剧敯鍋ワ紙灏忓叧瑁曞お楗帮級浠庡仴搴风殑鍏崇郴寮€濮嬩氦寰€鍚庣殑鏁呬簨銆俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2885449606.webp",
					Id:               13,
					Season:           300,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:41:20",
				},
			},
			VideoId:     13,
			PrettyName:  "涓嬭緢瀛愭垜鍐嶅ソ濂借繃 (鏇存柊鑷? 绗?3瀛?05)",
			MetaName:    "涓嬭緢瀛愭垜鍐嶅ソ濂借繃",
			AddDatetime: "2023-01-28 07:41:20",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 07:41:32",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35460658",
					TimeStr:          " 30鍒嗛挓",
					UptDatetime:      "2023-01-28 09:03:58",
					SetNum:           20,
					VideoId:          14,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2646807781.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-05-10(鏃ユ湰)']",
					Score:            0,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/35460658/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銇撱倢銇俱仹銆屼箖鏈ㄥ潅銇┿亾銇搞€嶃仹銆屻伓銈夈倞鏃呫€峔n<br/>\n銆€銆€銆屻儙銈偠銈偣銈儍銉勩€嶃仹銆屻偝銉炽儓銆嶃伀鎸戞垿銇椼仸銇嶃仧\n<br/>\n銆€銆€涔冩湪鍧?46銇湭鏉ャ倰鎷呫亞锛旀湡鐢熴仧銇°€俓n<br/>\n銆€銆€銇濄倱銇郊濂炽仧銇°亴銆佹銇寫鎴︺仚銈嬨伄銇€n<br/>\n銆€銆€銇倱銇ㄣ€屾槶鍜屾瓕璎°€?!\n<br/>\n銆€銆€寰€骞淬伄銉掋儍銉堛偨銉炽偘銈掋偒銉愩兗銇х啽鍞憋紒\n<br/>\n銆€銆€銇曘倝銇€佸ぇ寰℃墍鐢锋€ф瓕鎵嬨仺銇湰姘椼儑銉ャ偍銉冦儓銈傦紒\n<br/>\n銆€銆€鍙镐細銈掑嫏銈併倠銇伅銆佷粖鍥炲垵銈裤儍銈般仺銇倠銇恒亾銇便€俓n<br/>\n銆€銆€鍏冦儛銉炽儔銉炪兂銇澗闄板澶媷銇ㄣ€佹剰澶栥伀姝屻亴銈︺優銇勩偡銉ャ偊銉氥偆銇岀暘绲勩倰鐩涖倞涓娿亽銇俱仚銆俓n<br/>\n銆€銆€4鏈熺敓脳銇恒亾銇便€併仺銇勩亞銉曘儸銉冦偡銉ャ仾鍖栧鍙嶅繙銇倐銇旀敞鐩紒\n<br/>\n銆€銆€涔冩湪鍧?46銉?4鏈熺敓銇嬨倝鏈潵銇偣銈裤兗銇屻亶銇ｃ仺瑾曠敓銇欍倠锛乗n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2868302372.webp",
					Id:               31,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:03:58",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35814105",
					TimeStr:          " 25鍒嗛挓",
					UptDatetime:      "2023-01-28 07:41:40",
					SetNum:           20,
					VideoId:          14,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2870371904.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2021-10-12(鏃ユ湰)']",
					Score:            0,
					Year:             2021,
					PosterListUrl:    "https://movie.douban.com/subject/35814105/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€涔冩湪鍧?46銇?4鏈熺敓銇屻€屾槶鍜屾瓕璎°€嶃€屽钩鎴愩伄鍚嶆洸銆嶃伄銈儛銉笺伀鎸戞垿銇欍倠鐣祫銆傚徃浼氥伅銇婄瑧銇勩偝銉炽儞銉汇伜銇撱伇銇屽嫏銈併€佸綋鐣祫銇у垵銈炽儵銉溿仺銇倠銆傛斁閫佺祩浜嗗緦銆佹湭鍏枊鏄犲儚銈掍降銇涖仸銆屾湭鍏枊鏄犲儚銈傛偑銇忋仾銇勩仩銈嶃亞銆嶃伄銈裤偆銉堛儷銇ulu銇ч厤淇°€俓n<br/>\n銆€銆€2021骞?9鏈?28鏃ワ紙27鏃ユ繁澶滐級銆佺暘绲勩伄銈ㄣ兂銉囥偅銉炽偘銇с€併偡銉笺偤銉?2銇斁閫佹焙瀹氥亴鐧鸿〃銇曘倢銇焅n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2870371904.webp",
					Id:               16,
					Season:           200,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:41:40",
				},
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35936937",
					TimeStr:          " 22鍒嗛挓",
					UptDatetime:      "2023-01-28 07:41:32",
					SetNum:           1,
					VideoId:          14,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2874941397.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-04-26(鏃ユ湰)']",
					Score:            0,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/35936937/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€2022骞?2鏈堛伀銆佷箖鏈ㄥ潅46鏈熷緟銇柊鏄熴仺銇倠5鏈熺敓銇屾柊銇熴伀銉°兂銉愩兗銇ㄣ仐銇﹀姞鍏ャ€傘仢銈撱仾澶ф敞鐩伄褰煎コ銇熴仭銇屻€佹棭銇忋倐5鏈熺敓銇犮亼銇ч煶妤姐儛銉┿偍銉嗐偅銉笺伀鍒濇寫鎴?!4鏈熺敓銇屽嚭婕斻仐銇︺亜銇?1st銈枫兗銈恒兂銆佸厛杓┿儭銉炽儛銉笺倐鐧诲牬銇椼仧2nd銈枫兗銈恒兂銇у銇忋伄瑭遍銈掋仌銈夈仯銇熴€屼箖鏈ㄥ潅銈广偪銉艰獣鐢?!銆嶃伀5鏈熺敓銇屾寫鎴?!鏄拰&amp;骞虫垚銇儝銉冦儓銈姐兂銈般倰鐔卞敱銇椼伨銇?!鏂版檪浠ｃ倰鍒囥倞鎷撱亜銇︺亜銇忋儠銉儍銈枫儱銇郊濂炽仧銇°€備箖鏈ㄥ潅465鏈熺敓銇嬨倝銆佹槑鏃ャ伄銈广偪銉笺亴瑾曠敓銇欍倠!\n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2876056681.webp",
					Id:               15,
					Season:           300,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 07:41:32",
				},
			},
			VideoId:     14,
			PrettyName:  "涔冩湪鍧? 鏄庢槦璇炵敓 (鏇存柊鑷? 绗?3瀛?38)",
			MetaName:    "涔冩湪鍧傛槑鏄熻癁鐢?",
			AddDatetime: "2023-01-28 07:41:32",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:30:38",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35801591",
					TimeStr:          " 12鍒嗛挓",
					UptDatetime:      "2023-01-30 03:39:40",
					SetNum:           12,
					VideoId:          17,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2882701616.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-06(鏃ユ湰)']",
					Score:            6.4,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35801591/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鐢?#鍙ゅ窛浜斿娍#鍒涗綔婕敾銆?#鐢熻€屼负鐙楁垜寰堝垢绂?#銆嬪甯冨姩鐢诲寲鍐冲畾锛佸皢浜?2023骞存挱鍑猴紒\n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2883603402.webp",
					Id:               18,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ簲",
					AddDatetime:      "2023-01-28 08:30:38",
				},
			},
			VideoId:     17,
			PrettyName:  "鐢熻€屼负鐙? 鎴戝緢骞哥 鏃犱慨姝? (鏇存柊鑷?04)",
			MetaName:    "鐢熻€屼负鐙楁垜寰堝垢绂忔棤淇",
			AddDatetime: "2023-01-28 08:30:38",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:37:17",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/36055724",
					TimeStr:          "",
					UptDatetime:      "2023-01-28 08:37:17",
					SetNum:           9,
					VideoId:          18,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2884872482.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-05(鏃ユ湰)']",
					Score:            6.6,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/36055724/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€妯辩敽涓ぎ缃插垜浜嬭鐨勭帇鐗岃幉瑙佸厜杈咃紙婊ㄧ敯宀抽グ锛夛紝鍚埌鍙枒鐢峰瓙鎷掔粷璇㈤棶骞堕€冭蛋鐨勬秷鎭悗锛岀珛鍒昏刀鍒扮幇鍦恒€傚喎闈欏湴璇存湇鎸熸寔浜鸿川鐨勭敺瀛愶紝璁╀粬鎶曢檷鍙樊涓€鍙ｆ皵浜嗏€﹀氨鍦ㄨ繖鏃讹紝绐佺劧锛岀┛鐫€鍙屾帓鎵ｈタ瑁呮埓鐫€澧ㄩ暅鐨勯粦绀句細鎵撴壆鐨勭敺瀛愰棷鍏ワ紒鐢ㄧ啛缁冪殑鍔ㄤ綔鍒舵湇浜嗗彲鐤戜汉鍛樸€傜灛闂村钩鎭簨鎬佺殑杩欎釜鐢峰瓙锛屾鏄皟鍒板垜浜嬬鐨勬灦宸濊嫳鍎匡紙瑗垮矝绉€淇婇グ锛夈€備粬鏄粠鏈巺鐨勭粍缁囩姱缃绛栭儴锛屼篃灏辨槸鎵€璋撶殑鈥滀父鏆达紙鈥滄毚鍔涘洟瀵圭瓥鎼滄煡瀹樷€濈殑淇楃О锛夆€濅腑璋冪鐨勫垜璀﹀ぇ鍙斺€︺€傚氨鍦ㄨ繖鏃讹紝鍙戠敓浜嗗湪澶у鏁欐巿瀹跺伐浣滅殑濂崇瀹惰鍒烘潃鐨勪簨浠躲€傝嫳鍎垮拰鍏夎緟缁勬垚鎼。灞曞紑璋冩煡锛屽湪涓€璧疯皟鏌ョ殑杩囩▼涓紝鑻卞効瀵逛竴鍒囬兘寰堝畬缇庣殑鍏夎緟浜х敓浜嗚繚鍜屾劅鈥︼紒锛熷湪杩欐牱鐨勬儏鍐典笅锛?2浜哄紑濮嬪叧鐓ф柊涓婁换鐨勫垜璀︽按鏈ㄧ洿澶紙涓婄櫧鐭宠悓姝岄グ锛夛紝浣嗗疄闄呬笂鐩村ぎ鏄瑙嗗巺鍓€荤洃鐨勫コ鍎库€斺€旓紒锛焅n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2886047037.webp",
					Id:               19,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ簲",
					AddDatetime:      "2023-01-28 08:37:17",
				},
			},
			VideoId:     18,
			PrettyName:  "璀﹁鍘呭眬澶栦汉 (鏇存柊鑷?04)",
			MetaName:    "璀﹁鍘呭眬澶栦汉",
			AddDatetime: "2023-01-28 08:37:17",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:37:40",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35880801",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 08:37:40",
					SetNum:           12,
					VideoId:          19,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2884743880.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-05(鏃ユ湰)']",
					Score:            8.6,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35880801/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鏌愬ぉ锛屽閲岃共鐨勫晝鑰佹棌缁北鐪熷涓€瑙夐啋鏉ュ彂鐜拌嚜宸卞彉鎴愪簡鈥滃コ瀛╁瓙鈥濓紒锛熸褰撶湡瀵讳笉鐭ラ亾闀滃瓙閲岀殑缇庡皯濂虫槸鑷繁鑰岄櫡鍏ユ贩涔辩殑鏃跺€欙紝璺崇骇杩涘叆澶у鐨勭瀛﹀濡瑰缁北缇庢尝閲屽嚭鐜颁簡銆傚ス閫忛湶鍦ㄩギ鏂欓噷鍔犱簡涓€绉嶅鎬殑鑽墿锛乗n<br/>\n銆€銆€鐪熷鏈€杩?2骞翠竴鐩寸柉鐙傚畢瀹剁帺灏忛粍娓革紝鍋跺皵涓嶅緱宸叉墠浼氬伐浣滐紒绐佺劧鎴愪负濂冲瀛愬紑濮嬬敓娲荤殑鐪熷锛屽浜庡帟鎵€銆佹荡瀹ゃ€佽瀛愩€佽兏缃╃瓑濂充汉鐨勭敓娲诲畬鍏ㄤ笉鎳傗€﹀苟涓斾粬鍜岀編娉㈤噷涓鏃舵湡鐨勫悓瀛︾鏈堟灚鍜屽叾濡瑰绌楁湀妞涜璇嗐€俓n<br/>\n銆€銆€鐪熷鐨勬棩甯哥敓娲婚€愭笎鐑椆璧锋潵銆傚湪鎸佺画鐨勮嫤闅句腑锛屸€滃墠鈥濆摜鍝ョ殑鍛借繍浼氬浣?...锛乗n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2884738627.webp",
					Id:               20,
					Season:           100,
					PerUpdateTime:    "鍛ㄥ洓娣卞",
					AddDatetime:      "2023-01-28 08:37:40",
				},
			},
			VideoId:     19,
			PrettyName:  "鍒綋娆у凹閰变簡 (鏇存柊鑷?04)",
			MetaName:    "鍒綋娆у凹閰变簡",
			AddDatetime: "2023-01-28 08:37:40",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:38:55",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/36015584",
					TimeStr:          "",
					UptDatetime:      "2023-01-29 08:50:20",
					SetNum:           1,
					VideoId:          20,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2885509494.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-17(鏃ユ湰)']",
					Score:            7,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/36015584/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€璇ュ墽璁茶堪蹇樿鎯呮劅瀛ょ嫭鐢熸椿鐨?35宀佸浜х鍖荤敓闆閾冿紙鍚夐珮鐢遍噷瀛愰グ锛夊拰澶╃敓娌℃湁鍚鐨?25宀侀仐鐗╂暣鐞嗗笀鏌婁竴鏄燂紙鍖楁潙鍖犳捣楗帮級涓や汉鐨勬亱鐖辨晠浜嬨€傛柊浜哄浜х鍖荤敓路浣愪綈鏈ㄦ繁澶滐紙钘ゅ唸闈涢グ锛夌殑鐧诲満锛屽皢鍦ㄤ笁浜轰箣闂村睍寮€涓€娈?25宀併€?35宀併€?45宀佺殑10宀佸樊涓夎鎭嬨€俓n",
					VideoPosterUrl:   "https://img2.doubanio.com/view/photo/m/public/p2885510283.webp",
					Id:               21,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ笁",
					AddDatetime:      "2023-01-28 08:38:55",
				},
			},
			VideoId:     20,
			PrettyName:  "浜庢槦闄嶄箣澶? (鏇存柊鑷?02)",
			MetaName:    "浜庢槦闄嶄箣澶?",
			AddDatetime: "2023-01-28 08:38:55",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:39:12",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35765507",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-30 03:39:27",
					SetNum:           1,
					VideoId:          21,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2876189129.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-05(鏃ユ湰)']",
					Score:            5.8,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35765507/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€涓栫晫鏈€寮虹殑闂磋皪锛屼笘鐣屾渶楂樼殑楠楀眬锛乗n<br/>\n銆€銆€闃崇値瀹峰叡鍚岀敓娲荤殑瑙勫垯锛氫竷涓汉鍏卞悓鐢熸椿銆佸鍑虹殑鏃跺€欒璁ょ湡鐨勭帺銆佺敤涓€鍒囨墜娈垫墦鍊掓垜銆俓n<br/>\n銆€銆€鍚勫浗灞曞紑闂磋皪鈥滃奖涔嬫垬浜夆€濈殑涓栫晫銆備换鍔℃垚鍔熺巼100%锛屼絾鏄€ф牸鏈夊洶闅剧殑绮炬槑闂磋皪路鍏嬪姵鏂紝鍒涚珛浜嗘寫鎴樻浜＄巼瓒呰繃涔濇垚鐨勨€滀笉鍙兘浠诲姟鈥濈殑鏈哄叧鈥斺€旂伅銆備絾鏄紝琚€夊嚭鐨勬垚鍛樻槸娌℃湁瀹炶返缁忛獙鐨?7浣嶅皯濂炽€傛瘨鏉€銆侀櫡闃便€佽壊璇扁€斺€斾负浜嗗畬鎴愪换鍔★紝灏戝コ浠敮涓€鐣欎笅鐨勬墜娈靛氨鏄簰鐩告楠楀厠鍔虫柉锛屾垬鑳滄晫浜猴紒锛焅n",
					VideoPosterUrl:   "",
					Id:               22,
					Season:           100,
					PerUpdateTime:    "鍛ㄥ洓娣卞",
					AddDatetime:      "2023-01-28 08:39:12",
				},
			},
			VideoId:     21,
			PrettyName:  "闂磋皪鏁欏 (鏇存柊鑷?04)",
			MetaName:    "闂磋皪鏁欏",
			AddDatetime: "2023-01-28 08:39:12",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:39:15",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35633602",
					TimeStr:          " 50鍒嗛挓",
					UptDatetime:      "2023-01-28 10:48:15",
					SetNum:           7,
					VideoId:          22,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2882450463.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-12-28(鏃ユ湰)']",
					Score:            8.3,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/35633602/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€琛ㄩ潰椋庢櫙濡傜敾鐨勬潙搴勶紝鑳屽悗闅愯棌鐫€楠囦汉椋熶汉鏃忎紶闂汇€傚彶涓婃渶骞磋交鎴涚撼褰卞笣鏌充箰浼樺讥涓绘紨锛?12鏈?28鏃ュ甫浣犳繁鍏ラ浜烘棌鏉戣惤銆俓n<br/>\n銆€銆€璀﹀畼闃垮窛澶ф偀锛堟煶涔愪紭寮ラグ锛夎璋冩淳鑷冲北闂村皬闀団€滀緵鑺辨潙鈥濓紝涓庡瀛愬拰濂冲効涓€璧峰埌褰撳湴灞曞紑鏂扮敓娲荤殑浠栵紝鍗撮亣涓婁竴杩炰覆闇囨儕鐨勪簨浠讹紝鍥犳浘鍚鈥滄潙涓殑浜轰細鍚冧汉鈥濓紝璁╀粬閫愭笎寮€濮嬬浉淇¤繖涓娉曘€俓n<br/>\n銆€銆€鍓ч泦鏀圭紪鑷簩瀹鏄?2018骞村紑濮嬭繛杞界殑婕敾锛屼綔鍝佸悕銆奊annibal銆嬪彇鑷狧annibal锛堟眽灏兼嫈锛夌殑淇勬枃璇绘硶銆俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2885651715.webp",
					Id:               23,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ笁",
					AddDatetime:      "2023-01-28 08:39:15",
				},
			},
			VideoId:     22,
			PrettyName:  "鍣骸鏉? (鏇存柊鑷?06)",
			MetaName:    "鍣骸鏉?",
			AddDatetime: "2023-01-28 08:39:15",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:39:20",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35373068",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 08:39:20",
					SetNum:           20,
					VideoId:          23,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2880340690.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2022-10-05(鏃ユ湰)']",
					Score:            7.6,
					Year:             2022,
					PosterListUrl:    "https://movie.douban.com/subject/35373068/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆?#鎯宠鎴愪负褰变箣瀹炲姏鑰咃紒#(闄般伄瀹熷姏鑰呫伀銇倞銇熴亸銇?!銆佹垜鎯虫垚涓哄奖涔嬪己鑰?)銆嬫槸鐢遍€㈡辰澶т粙鍒涗綔锛屼笢瑗挎彃鐢荤殑杞诲皬璇翠綔鍝併€傝繎鏃ワ紝璇ヤ綔瀹ｅ竷鍔ㄧ敾鍖栦紒鍒掕繘琛屼腑~\n<br/>\n銆€銆€绠€浠嬶細灏戝勾甯痉鎲ф啲鐫€浠ヨ矾浜鸿韩鍒嗛殣钘忚嚜韬姏閲忥紝涓嶄负浜虹煡鍦颁粙鍏ユ晠浜嬶紝灞曠幇瀹炲姏鐨勩€屽奖涔嬪己鑰呫€峔n<br/>\n銆€銆€杞敓鍒板紓涓栫晫鍚庯紝浼佸浘鍏呭垎浜彈杩欑璁惧畾鐨勫腑寰凤紝涓轰簡鍑绘簝濡勬兂涓殑鏁屼汉銆岄粦鏆楁暀鍥€€嶈€屾殫涓ぇ鏄捐韩鎵嬨€俓n<br/>\n銆€銆€鐒惰€岋紝杩欎釜鏁欏洟浼间箮鐪熺殑瀛樺湪鈥︹€︼紵\n<br/>\n銆€銆€鍚屾椂锛屽洜涓轰粬椤哄娍鏀朵负閮ㄤ笅鐨勫皯濂充滑銆屼細閿欐剰銆嶏紝甯痉鍦ㄤ竴鏃犳墍鐭ョ殑鐘舵€佷笅鎴愪簡鐪熸鐨勩€屽奖涔嬪己鑰呫€嶏紝涓€琛屼汉寤虹珛璧锋潵鐨勩€屾殫褰卞涵鍥€嶏紝灏嗘鐏繖涓栦笂鐨勯粦鏆椻攢銆俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2880363057.webp",
					Id:               24,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ笁娣卞",
					AddDatetime:      "2023-01-28 08:39:20",
				},
			},
			VideoId:     23,
			PrettyName:  "鎯宠鎴愪负褰变箣瀹炲姏鑰? (鏇存柊鑷?17)",
			MetaName:    "鎯宠鎴愪负褰变箣瀹炲姏鑰?",
			AddDatetime: "2023-01-28 08:39:20",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 08:39:23",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35745547",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-28 08:39:23",
					SetNum:           11,
					VideoId:          24,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2884179280.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-11(鏃ユ湰)']",
					Score:            8.5,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35745547/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鐢变簬涓嶆柇鎵╁ぇ鐨勨€滈洩娴封€濓紝澶у湴鍑犱箮娑堝け鐨勫紓涓栫晫鈥斺€擻n<br/>\n銆€銆€浜轰滑鍦ㄥ法鏍戔€滆建閬撴爲鈥濈殑鏍归儴鍜屼粠椤堕儴寤朵几鍑烘潵鐨勨€滃ぉ鑶溾€濅笂鍕夊己搴︽棩銆俓n<br/>\n銆€銆€澶╄啘鐨勫皯骞村崱绾冲拰鍦颁笂鐨勫皯濂宠帀鑾夊搱鐩搁亣鐨勬椂鍊欙紝\n<br/>\n銆€銆€鏀瑰彉杩欎釜鍗冲皢姣佺伃鐨勪笘鐣岀殑鏁呬簨锛屽紑濮嬩簡鈥斺€擻n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2876493036.webp",
					Id:               25,
					Season:           100,
					PerUpdateTime:    "鍛ㄥ洓",
					AddDatetime:      "2023-01-28 08:39:23",
				},
			},
			VideoId:     24,
			PrettyName:  "澶ч洩娴风殑鍑撼 (鏇存柊鑷?03)",
			MetaName:    "澶ч洩娴风殑鍑撼",
			AddDatetime: "2023-01-28 08:39:23",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:36:10",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35785946",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-29 11:57:33",
					SetNum:           12,
					VideoId:          27,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2880847310.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-07(鏃ユ湰)']",
					Score:            8.2,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35785946/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€瑗垮巻5012骞淬€傜獊鐒跺叆渚靛湴鐞冪殑锛滃鏄熶汉锛炰笌鍏跺埗閫犵殑锛滄満姊扮敓鐗╋紴瀵艰嚧浜虹被闈复鐏骸鍗辨満銆俓n<br/>\n銆€銆€浠呭瓨鐨勪汉绫婚€冭嚦鏈堢悆锛屼负浜嗗ず鍥炲湴鐞冿紝鍒╃敤锛滀汉閫犱汉锛炲＋鍏靛睍寮€鍙嶆敾浣滄垬銆俓n<br/>\n銆€銆€鐒惰€屾棤闄愬鍔犵殑锛滄満姊扮敓鐗╋紴闃绘尅鍦ㄥ墠锛屾垬浜夐櫡鍏ヨ兌钁楃姸鎬併€俓n<br/>\n銆€銆€浣滀负鏈€缁堝叺鍣紝浜虹被娲鹃仯鏂板瀷浜洪€犱汉锛滃瘎鍙讹紴閮ㄩ槦鑷冲湴鐞冦€傚垰琚淳寰€鍦扮悆鐨勶紲2B锛炰笌鍏堣璋冩煡鍛橈紲9S锛炰細鍚堬紝涓€鍚屾墽琛屼换鍔★紝鍗村湪閫斾腑閬囪璁稿绁炵闅捐В鐨勭幇璞♀€︹€︺€俓n<br/>\n銆€銆€杩欐槸鍏充簬涓轰汉绫昏€屾垬锛屾棤鐢熷懡锛滀汉閫犱汉锛炵殑鏁呬簨锛嶏紞\n<br/>\n銆€銆€PS锛欰utomata鎸囩殑鏄€滆嚜鍔ㄤ汉褰⑩€濓紝鍒啀鏈烘绾厓姹傛眰浜嗐€俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2886624408.webp",
					Id:               33,
					Season:           100,
					PerUpdateTime:    "鍛ㄥ叚娣卞",
					AddDatetime:      "2023-01-28 09:36:10",
				},
			},
			VideoId:     27,
			PrettyName:  "灏煎皵 鑷姩浜哄舰 (鏇存柊鑷?03)",
			MetaName:    "灏煎皵鑷姩浜哄舰",
			AddDatetime: "2023-01-28 09:36:10",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:39:19",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35727023",
					TimeStr:          " 40鍒嗛挓",
					UptDatetime:      "2023-01-29 09:42:58",
					SetNum:           9,
					VideoId:          28,
					PosterCache:      "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2831719427.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-12(鏃ユ湰)']",
					Score:            8.1,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35727023/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鑺傜洰缁熺鏄灊瑁曞拰銆佸埗浣滀汉宸濇潙鍏冩皵锛屽姞涓婃．涓冭彍鍜屽嚭鍙ｅ甯岀瓑璞崕婕斿憳闃靛锛屾惡鎵嬪皢鍗栫牬200涓囨湰鐨勭伀绾㈡极鐢绘惉涓婅崸灞忥紒鏁呬簨浠ヤ含閮界殑鑹轰紟鍖轰负鑸炲彴锛岃杩拌垶浼庯紙鑹轰紟瀛﹀緬锛夊爣鍜屾枡鐞嗕汉瀛ｄ唬鍦ㄨ垶浼庡鑸嶉噷鐨勬棩瀛愶紝璇夎鐢辩編椋熶氦缁囪€屾垚鐨勬棩甯哥敓娲汇€俓n<br/>\n銆€銆€婕敾鍘熻憲锛氬皬灞辩埍瀛愮殑銆婅垶浼庡鐨勬枡鐞嗕汉銆嬶紙灏忓棣嗐€婂懆鍒婂皯骞碨unday銆嬪垔鐧伙級\n<br/>\n銆€銆€鑺傜洰缁熺锛氭槸鏋濊鍜孿n<br/>\n銆€銆€鍒朵綔浜猴細宸濇潙鍏冩皵\n<br/>\n銆€銆€瀵兼紨锛氭槸鏋濊鍜屻€佹触閲庣埍銆佸ゥ灞卞ぇ鍙层€佷綈钘ゅ揩纾╘n<br/>\n銆€銆€缂栧墽锛氭槸鏋濊鍜屻€佺爞鐢伴夯缇庛€佹触閲庣埍銆佸ゥ灞卞ぇ鍙层€佷綈钘ゅ揩纾╘n<br/>\n銆€銆€涓绘紨锛氭．涓冭彍銆佸嚭鍙ｅ甯孿n<br/>\n銆€銆€婕斿憳锛氳幊鐢板僵鐝犮€佸煄妗у悘銆佺鍦版瀛愩€佽嫢鏌崇惔瀛愩€佸崡鐞村銆佷腑宸濋泤涔熴€佸寳鏉戞湁璧峰搲銆佸熬缇庡埄寰枫€佸彜棣嗗娌汇€佹埛鐢版儬瀛愩€佺櫧鐭冲姞浠ｅ瓙銆佹澗鍧傚簡瀛愩€佹ˉ鏈埍銆佹澗鍐堣寜浼樸€佷簳娴︽柊銆佸父鐩樿吹瀛怽n<br/>\n銆€銆€鎽勫奖锛氳繎钘ら緳浜篭n<br/>\n銆€銆€鐏厜锛氬熬涓嬭崳娌籠n<br/>\n銆€銆€鏀堕煶锛氬瘜鐢板拰褰n<br/>\n銆€銆€缇庢湳鎸囧锛氱鐢伴槼骞砛n<br/>\n銆€銆€甯冩櫙锛氶厭浜曟嫇纾╘n<br/>\n銆€銆€鏈嶈璁捐锛氫紛钘や綈鏅哄瓙\n<br/>\n銆€銆€濡嗗彂璁捐锛氬媷瑙佽儨褰n<br/>\n銆€銆€椋熺墿閫犲瀷...\n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2838201344.webp",
					Id:               34,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:39:19",
				},
			},
			VideoId:     28,
			PrettyName:  "鑸炰紟瀹剁殑鏂欑悊浜? (鏇存柊鑷?09)",
			MetaName:    "鑸炰紟瀹剁殑鏂欑悊浜?",
			AddDatetime: "2023-01-28 09:39:19",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:39:28",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/35925201",
					TimeStr:          " 24鍒嗛挓",
					UptDatetime:      "2023-01-29 06:44:00",
					SetNum:           12,
					VideoId:          29,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2884921062.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-19(鏃ユ湰缃戠粶)']",
					Score:            6.6,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/35925201/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€鎭愭€栨极鐢诲ぇ甯堜紛钘ゆ鼎浜岀殑鏁呬簨灏嗕互鍔ㄧ敾鍓ч泦鐨勫舰寮忕幇韬崸骞曘€俓n<br/>\n銆€銆€鎭愭€栨极鐢讳箣鐜嬩紛钘ゆ鼎浜岀殑鎭愭€栨极鐢绘澃浣滀簬2023骞翠互鍔ㄦ极鍓ч泦鐨勫舰寮忕櫥闄哊etflix銆俓n<br/>\n銆€銆€浼婅棨鐨勪綔鍝佸崄鍒嗕赴瀵岋紝鍏朵腑20涓互鈥滅柉鐙傗€濅负鍏卞悓涓婚鐨勪紭绉€鏁呬簨灏嗚璇ユ敼缂栦负鍔ㄧ敾鍓ч泦锛屾晠浜嬪寘鎷€婁汉澶存皵鐞冦€嬨€婂瘜姹熴兓鐓х墖銆嬨€婂洓閬撳鐨勬埧闂淬€嬪拰銆婁镜鍏ヨ€呫€嬨€俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2886743449.webp",
					Id:               35,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:39:28",
				},
			},
			VideoId:     29,
			PrettyName:  "浼婅棨娑︿簩鐙傜儹 鏃ユ湰鎭愭€栨晠浜? (鏇存柊鑷?12)",
			MetaName:    "浼婅棨娑︿簩鐙傜儹鏃ユ湰鎭愭€栨晠浜?",
			AddDatetime: "2023-01-28 09:39:28",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:40:40",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/25848328",
					TimeStr:          " 60-85鍒嗛挓",
					UptDatetime:      "2023-01-30 02:21:38",
					SetNum:           9,
					VideoId:          33,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2884221114.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-15(缇庡浗)']",
					Score:            9.1,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/25848328/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆婃渶鍚庣敓杩樿€呫€嬫槸鐢盚BO鍑哄搧锛岃鍓ф敼缂栬嚜椤界毊鐙椾簬2013骞?6鏈?14鏃ユ帹鍑虹殑PlayStation骞冲彴鍚屽悕娓告垙銆傝杩颁簡鍦ㄧ幇浠ｆ枃鏄庤鎽ф瘉鐨勪簩鍗佸勾鍚庯紝浜虹被鍥犵幇浠ｄ紶鏌撶梾鑰岄潰涓寸粷绉嶅嵄鏈猴紝骞稿瓨鐨勪汉绫讳负浜嗙敓瀛樿嚜鐩告畫鏉€銆備腑骞寸敺鎬ц蛋绉佺姱涔斿皵锛堜僵寰风綏路甯曟柉鍗￠グ锛変负浜嗗畬鎴愨€滅伀钀も€濈粍缁囬棰嗙帥鐞筹紙姊呭皵路涓瑰痉閲屽楗帮級鐨勬墭浠橈紝甯︾潃14宀佸皯濂宠壘鑾夛紙璐濇媺路鎷夊榻愰グ锛変竴鍚岃笍鍑虹敱鍐涢槦淇濇姢鐨勭柅鎯呴殧绂诲尯锛岀┛瓒婂寲涓哄簾澧熶笡鏋楃殑澶ч兘浼氥€傞潰瀵圭梾姣掓劅鏌撳彉绉嶄汉绫讳笌鍏朵粬骞稿瓨鑰呴泦鍥㈠▉鑳侊紝灞曞紑浜嗕竴鍦烘敼鍙樹袱浜轰竴鐢熺殑娣卞埢鏃呯▼銆俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2886639975.webp",
					Id:               38,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ竴",
					AddDatetime:      "2023-01-28 09:40:40",
				},
			},
			VideoId:     33,
			PrettyName:  "鏈€鍚庣敓杩樿€? (鏇存柊鑷?02)",
			MetaName:    "鏈€鍚庣敓杩樿€?",
			AddDatetime: "2023-01-28 09:40:40",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:40:49",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/36156235",
					TimeStr:          " 55鍒嗛挓",
					UptDatetime:      "2023-01-30 02:21:09",
					SetNum:           10,
					VideoId:          34,
					PosterCache:      "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2886331572.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2023-01-08(鏃ユ湰)']",
					Score:            9.1,
					Year:             2023,
					PosterListUrl:    "https://movie.douban.com/subject/36156235/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€33宀佺殑鍗曡韩濂虫€ц繎钘ら夯缇庯紙瀹夎棨妯遍グ锛夛紝鍦ㄨ€佸鐨勫競褰规墍宸ヤ綔鐨勫ス杩囩潃骞冲嚒鐨勭敓娲汇€傝€屾湁涓€澶╋紝杩戣棨鍙戠幇濂圭獊鐒跺嚭鐜板湪浜嗗浜х鐨勭梾搴婁笂锛岀溂鍓嶅嚭鐜颁簡杩樺勾杞荤殑鐖舵瘝銆俓n",
					VideoPosterUrl:   "https://img1.doubanio.com/view/photo/m/public/p2885572548.webp",
					Id:               39,
					Season:           100,
					PerUpdateTime:    "鍛ㄤ竴",
					AddDatetime:      "2023-01-28 09:40:49",
				},
			},
			VideoId:     34,
			PrettyName:  "閲嶅惎浜虹敓 (鏇存柊鑷?03)",
			MetaName:    "閲嶅惎浜虹敓",
			AddDatetime: "2023-01-28 09:40:49",
		},
		NoNameObject{
			UptDatetime: "2023-01-28 09:40:54",
			Details: Details{
				NoNameObject1427828239{
					DescriptionUrl:   "https://movie.douban.com/subject/26367636",
					TimeStr:          " 25鍒嗛挓 / 30鍒嗛挓锛堝惈骞垮憡锛?",
					UptDatetime:      "2023-01-28 10:47:53",
					SetNum:           1,
					VideoId:          35,
					PosterCache:      "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2621865024.webp",
					OfficialWebsite:  "",
					ReleasedDateStr:  "['2015-04-19(鏃ユ湰)']",
					Score:            9.5,
					Year:             2015,
					PosterListUrl:    "https://movie.douban.com/subject/26367636/photos?type=R&sortby=size",
					VideoDescription: "銆€銆€銆婁箖鏈ㄥ潅宸ヤ簨涓€嬩负鏃ユ湰濂冲瓙鍋跺儚鍥綋涔冩湪鍧?46鐨勫啝鍚嶇患鑹鸿妭鐩紝鐢变笢浜數瑙嗙綉鎴愬憳涔嬩竴鐨勭埍鐭ョ數瑙嗗彴鍒朵綔锛岃嚜2015骞?4鏈?19鏃ヨ捣浜庢棩鏈笢浜數瑙嗙綉鎾嚭銆傛湰鑺傜洰鎺ユ。鍓嶅啝鍚嶇患鑹恒€婁箖鏈ㄥ潅鍦ㄥ摢閲岋紵銆嬶紝鎾嚭鏃堕棿涓烘棩鏈綋鍦版椂闂存瘡鍛ㄦ棩24鏃舵暣鑷?24鏃?30鍒嗐€俓n<br/>\n銆€銆€涓庛€婁箖鏈ㄥ潅鍦ㄥ摢閲岋紵銆嬬浉鍚岋紝鑺傜洰涓绘寔浜轰粛鐢辨悶绗戠粍鍚堥钑変汉鎷呭綋銆傝妭鐩悓鏃剁户鎵夸簡鍓嶄綔鐨勯儴鍒嗗父瑙勪紒鍒掞紝濡傚洟浣撴瘡寮犲崟鏇插彂琛ㄥ墠鐨勨€滈€夋嫈鎴愬憳绔欎綅鍏紑鈥濄€佸崟鏇插彂琛ㄥ悗鐨勨€滃ぇ鍗栫鎰库€濈瓑绛夈€傚埗浣滅粍涔熷父涓庣粍鍚堟垚鍛樺拰涓绘寔浜鸿繘琛岄棶鍗疯皟鏌ユ垨鐩存帴浜ゆ祦锛岄€氳繃鍚堜綔鏉ュ疄鐜版帹闄堝嚭鏂帮紝鍏朵腑璇炵敓浜嗚濡備笌棣欒晧浜烘棩鏉戝媷绾悎浣滅殑鐩稿叧缁忓吀浼佸垝銆備袱浣嶄富鎸佷汉涔熷洜鑷洟浣撶粨鎴愪互鏉ヤ究鍥哄畾涓绘寔鍥綋缁艰壓鑰岃璧嬩簣鈥滃畼鏂瑰摜鍝ワ紙鍏紡銇婂厔銇°們銈擄級鈥濈殑鐖辩О銆俓n<br/>\n銆€銆€姝ゅ锛岄€氳繃绐佸嚭绗戠偣鐨勫瓧骞曟í骞呬互鍙婂舰璞＄敓鍔ㄧ殑鎻掑浘绛夎璁★紝鍒朵綔缁勪篃鍔涙眰鑳借涓嶄簡瑙ｄ箖鏈ㄥ潅46鐨勮浼椾篃鑳芥劅鍙楀埌鑺傜洰鐨勪箰瓒ｃ€俓n",
					VideoPosterUrl:   "https://img9.doubanio.com/view/photo/m/public/p2291842365.webp",
					Id:               40,
					Season:           100,
					PerUpdateTime:    "",
					AddDatetime:      "2023-01-28 09:40:54",
				},
			},
			VideoId:     35,
			PrettyName:  "涔冩湪鍧傚伐浜嬩腑 (鏇存柊鑷?395)",
			MetaName:    "涔冩湪鍧傚伐浜嬩腑",
			AddDatetime: "2023-01-28 09:40:54",
		},
	},
}
